import {
  DEFAULT_STANDING_ORDERS,
  type Campaign,
  type WorldState,
} from "@griffty/domain";

export function emptyWorld(now = new Date()): WorldState {
  const iso = now.toISOString();
  const campaigns: Campaign[] = [
    {
      id: "cmp_meta_prospect",
      platform: "meta",
      name: "WNY discovery Advantage+",
      objective: "traffic",
      kind: "prospecting",
      dailyBudgetUsd: 12,
      status: "active",
      utm: { source: "meta", medium: "paid", campaign: "wny_discovery", content: "hook_a" },
      kpis: { roas: 1.1, cpa_usd: 8.4, cpm: 6.2, ctr: 0.9 },
      creativeIds: [],
    },
    {
      id: "cmp_google_brand",
      platform: "google",
      name: "Doc Weather brand search",
      objective: "leads",
      kind: "branded",
      dailyBudgetUsd: 8,
      status: "active",
      utm: { source: "google", medium: "paid", campaign: "brand", content: "exact" },
      kpis: { roas: 3.4, cpa_usd: 4.1, cpm: 11, ctr: 4.2 },
      creativeIds: [],
    },
    {
      id: "cmp_meta_retarget",
      platform: "meta",
      name: "Video viewers retarget",
      objective: "sales",
      kind: "retargeting",
      dailyBudgetUsd: 6,
      status: "active",
      utm: { source: "meta", medium: "paid", campaign: "viewers", content: "cut_b" },
      kpis: { roas: 2.6, cpa_usd: 5.0, cpm: 9.1, ctr: 1.4 },
      creativeIds: [],
    },
  ];

  return {
    operator: {
      uid: process.env.OPERATOR_UID ?? "operator_1",
      displayName: "Charles Clottin",
      tz: "America/New_York",
      geo: "US",
      availableMinutesToday: 90,
      riskTolerance: "low",
      createdAt: iso,
    },
    policy: { ...DEFAULT_STANDING_ORDERS },
    cashUsd: 40,
    adsAccounts: [
      {
        platform: "google",
        balanceUsd: 42,
        floorUsd: 100,
        bufferUsd: 25,
        status: "ok",
        lastPolledAt: iso,
      },
      {
        platform: "meta",
        balanceUsd: 38,
        floorUsd: 100,
        bufferUsd: 25,
        status: "ok",
        lastPolledAt: iso,
      },
      {
        platform: "tiktok",
        balanceUsd: 20,
        floorUsd: 100,
        bufferUsd: 25,
        status: "ok",
        lastPolledAt: iso,
      },
      {
        platform: "x",
        balanceUsd: 15,
        floorUsd: 100,
        bufferUsd: 25,
        status: "ok",
        lastPolledAt: iso,
      },
    ],
    wallets: [
      {
        id: "wal_treasury",
        role: "treasury",
        address: "pending",
        chain: "solana",
        watchOnly: true,
        assets: [{ symbol: "ETH", amount: 0.12, usdMark: 312 }],
        lastPolledAt: iso,
      },
      {
        id: "wal_burner",
        role: "burner",
        address: "pending",
        chain: "solana",
        watchOnly: true,
        assets: [],
        lastPolledAt: iso,
      },
      {
        id: "wal_session",
        role: "session",
        address: "pending",
        chain: "solana",
        watchOnly: true,
        assets: [],
        lastPolledAt: iso,
      },
    ],
    opportunities: [],
    tasks: [],
    ledger: [],
    campaigns,
    creatives: [],
    alerts: [],
    events: [],
    platforms: [
      {
        id: "respondent",
        name: "Respondent",
        tier: "A",
        enrolled: true,
        officialBaseUrl: "https://www.respondent.io",
        kycStatus: "complete",
        lastPayoutAt: null,
        residualValueUsd: 40,
      },
      {
        id: "swagbucks",
        name: "Swagbucks",
        tier: "B",
        enrolled: true,
        officialBaseUrl: "https://www.swagbucks.com",
        kycStatus: "complete",
        lastPayoutAt: null,
        residualValueUsd: 8,
      },
      {
        id: "honeygain",
        name: "Honeygain",
        tier: "D",
        enrolled: true,
        officialBaseUrl: "https://www.honeygain.com",
        kycStatus: "none",
        lastPayoutAt: null,
        residualValueUsd: 12,
      },
      {
        id: "coinbase",
        name: "Coinbase Learn",
        tier: "F",
        enrolled: true,
        officialBaseUrl: "https://www.coinbase.com",
        kycStatus: "complete",
        lastPayoutAt: null,
        residualValueUsd: 5,
      },
      {
        id: "weatherxm",
        name: "WeatherXM",
        tier: "E",
        enrolled: true,
        officialBaseUrl: "https://weatherxm.com",
        kycStatus: "none",
        lastPayoutAt: null,
        residualValueUsd: 0,
      },
    ],
    kpiDaily: [],
    signIntents: [],
    killSwitch: {
      active: false,
      reasons: [],
      pauseNewSignups: false,
      pauseColdAdSpend: false,
    },
    socialPosts: [],
    notifications: [],
    ipVault: { tracks: [], lastAuditAt: null },
    cycleId: "init",
    updatedAt: iso,
  };
}
