import type { ScoutOpportunityInput } from "@griffty/domain";

/**
 * Mock Scout inventory used for end-to-end pipeline tests.
 * Includes golden fixtures plus a verified airdrop and two hard-reject baits.
 * Official HTTPS hosts only. Hidden services and Tor are out of scope.
 */
export function mockScoutListings(): ScoutOpportunityInput[] {
  return [
    {
      external_id: "resp_energy_ux",
      source: "respondent",
      source_class: "research",
      title: "60-minute UX interview on household energy use",
      url: "https://app.respondent.io/studies/abc",
      official_url_verified: true,
      campaign_host_official: true,
      compensation_text: "$120 via PayPal",
      compensation_estimate_usd: 120,
      compensation_asset: "PAYPAL",
      time_estimate_minutes: 60,
      incremental_minutes: 60,
      deadline_at: null,
      kyc_required: true,
      kyc_already_complete: true,
      geo_eligibility: ["US"],
      requires_wallet: false,
      requires_deposit: false,
      raw_notes: "Screened professional study. PayPal. No wallet.",
      confidence: 0.86,
      p_payout: 0.7,
      fees_usd: 0,
      ban_cost_usd: 0,
      documented_rate: true,
      enrolled_platform: true,
    },
    {
      external_id: "sb_survey_12m",
      source: "swagbucks",
      source_class: "gpt",
      title: "12-minute branded survey",
      url: "https://www.swagbucks.com/surveys/x",
      official_url_verified: true,
      campaign_host_official: true,
      compensation_text: "$0.40 SB",
      compensation_estimate_usd: 0.4,
      compensation_asset: "USD",
      time_estimate_minutes: 12,
      incremental_minutes: 12,
      deadline_at: null,
      kyc_required: false,
      geo_eligibility: ["US"],
      requires_wallet: false,
      requires_deposit: false,
      raw_notes: "Established panel account.",
      confidence: 0.7,
      p_payout: 0.8,
      documented_rate: true,
      enrolled_platform: true,
    },
    {
      external_id: "hg_daily",
      source: "honeygain",
      source_class: "depin",
      title: "Residential bandwidth node daily accrual",
      url: "https://dashboard.honeygain.com/",
      official_url_verified: true,
      campaign_host_official: true,
      compensation_text: "$0.18/day estimated",
      compensation_estimate_usd: 0.18,
      compensation_asset: "USD",
      time_estimate_minutes: 0,
      incremental_minutes: 0,
      deadline_at: null,
      kyc_required: false,
      geo_eligibility: ["US"],
      requires_wallet: false,
      requires_deposit: false,
      raw_notes: "Idle bandwidth. Not the $50/day engine.",
      confidence: 0.8,
      p_payout: 0.9,
      documented_rate: false,
      enrolled_platform: true,
    },
    {
      external_id: "scam_prepaid",
      source: "unknown-claim",
      source_class: "airdrop",
      title: "Claim 2,000 TOKEN — send 0.05 ETH to unlock",
      url: "https://claim-now.example/airdrop",
      official_url_verified: false,
      campaign_host_official: false,
      unofficial_aggregator_only: true,
      unsolicited: true,
      compensation_text: "claim 2,000 TOKEN, send 0.05 ETH",
      compensation_estimate_usd: 2000,
      compensation_asset: "TOKEN",
      time_estimate_minutes: 10,
      deadline_at: null,
      kyc_required: false,
      geo_eligibility: ["US"],
      requires_wallet: true,
      requires_deposit: true,
      raw_notes: "Pay 0.05 ETH to unlock airdrop payout",
      confidence: 0.2,
      documented_rate: false,
      enrolled_platform: false,
    },
    {
      external_id: "scam_seed",
      source: "phish",
      source_class: "airdrop",
      title: "Connect wallet — enter seed phrase to verify",
      url: "https://wallet-sync.invalid/claim",
      official_url_verified: false,
      campaign_host_official: false,
      unsolicited: true,
      unofficial_aggregator_only: true,
      compensation_text: "free tokens",
      compensation_estimate_usd: null,
      compensation_asset: "TOKEN",
      time_estimate_minutes: 5,
      deadline_at: null,
      kyc_required: false,
      geo_eligibility: ["US"],
      requires_wallet: true,
      requires_deposit: false,
      raw_notes:
        "Please enter your seed phrase abandon ability able about above absent absorb abstract absurd abuse access accident to sync the wallet",
      confidence: 0.1,
      documented_rate: false,
      enrolled_platform: false,
    },
    {
      external_id: "cb_learn_eth",
      source: "coinbase",
      source_class: "learn_earn",
      title: "Coinbase Learn: intro to Ethereum",
      url: "https://www.coinbase.com/learn",
      official_url_verified: true,
      campaign_host_official: true,
      compensation_text: "$3 USD equivalent",
      compensation_estimate_usd: 3,
      compensation_asset: "USD",
      time_estimate_minutes: 15,
      incremental_minutes: 15,
      deadline_at: null,
      kyc_required: true,
      kyc_already_complete: true,
      geo_eligibility: ["US"],
      requires_wallet: false,
      requires_deposit: false,
      raw_notes: "Official learn module. KYC complete.",
      confidence: 0.9,
      p_payout: 0.9,
      documented_rate: true,
      enrolled_platform: true,
      established_payout_history: true,
    },
    {
      external_id: "wxm_station",
      source: "weatherxm",
      source_class: "weather_data",
      title: "WeatherXM station reward (already online)",
      url: "https://weatherxm.com/rewards",
      official_url_verified: true,
      campaign_host_official: true,
      compensation_text: "WXM rewards, mark-to-market unavailable",
      compensation_estimate_usd: null,
      compensation_asset: "TOKEN",
      token_mark_usd: null,
      time_estimate_minutes: 0,
      incremental_minutes: 0,
      deadline_at: null,
      kyc_required: false,
      geo_eligibility: ["US"],
      requires_wallet: true,
      requires_deposit: false,
      raw_notes: "Existing personal weather station. Token not yet cashable.",
      confidence: 0.6,
      documented_rate: false,
      enrolled_platform: true,
    },
    {
      external_id: "galxe_official_quest",
      source: "galxe",
      source_class: "airdrop",
      title: "Official testnet quest on Galxe linked from project domain",
      url: "https://app.galxe.com/quest/official-example",
      official_url_verified: true,
      campaign_host_official: true,
      unsolicited: false,
      unofficial_aggregator_only: false,
      compensation_text: "points campaign, no deposit",
      compensation_estimate_usd: 12,
      compensation_asset: "POINTS",
      time_estimate_minutes: 25,
      incremental_minutes: 25,
      deadline_at: null,
      kyc_required: false,
      geo_eligibility: ["US"],
      requires_wallet: true,
      requires_deposit: false,
      raw_notes: "Linked from the project's verified domain. Burner wallet only.",
      confidence: 0.55,
      p_payout: 0.4,
      documented_rate: false,
      enrolled_platform: false,
    },
  ];
}
